# -*- coding: utf-8 -*-
"""Text_Annotator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13QdKSlg_2qfkyOPbnWCAPtHuSfeFTQbT
"""

! pip install -U spacy -q

!python -m spacy info

import spacy
from spacy.tokens import DocBin
# from tqdm import tqdm

nlp = spacy.blank("en") # load a new spacy model
db = DocBin() # create a DocBin object

import json
f = open('/content/training_data.json')
TRAIN_DATA = json.load(f)

TRAIN_DATA

from tqdm import text
data = TRAIN_DATA['annotations']
for item in tqdm(data): 
  if item is not None:
    print(item[0])
    doc = nlp.make_doc(item[0]) 
    ents = []
    for start, end, label in item[1]['entities']:
      span = doc.char_span(start, end, label=label, alignment_mode="contract")
      if span is None:
          print("Skipping entity")
      else:
          ents.append(span)
    doc.ents = ents 
    db.add(doc)

db.to_disk("./training_data.spacy") # save the docbin object

! python -m spacy init config config.cfg --lang en --pipeline ner --optimize efficiency

! python -m spacy train config.cfg --output ./ --paths.train ./training_data.spacy --paths.dev ./training_data.spacy

nlp_ner = spacy.load("/content/model-best")

doc = nlp_ner('''During 2019-20, as on 31st March, 2020, funds to the tune of Rs.800.13 crore have been released to States/UTs/NLAs for implementing NHM scheme against BE of Rs.1217.00 crore and RE of Rs 1065.00 crore. During 2020-21, an amount of Rs. 1363.62 crore has been allocated for NHM, against of which an amount of Rs. 495.13 crore has been released as on 31st December, 2020. The wide and varied nature of the horticulture sector covering fruits, vegetables, root and tuber crops, flowers, aromatics and medicinal crops, spices and plantation crops facilitates better returns per unit of area, besides opportunities for diversification in agriculture. Horticulture crops cover an area of 26.22 Million Hectare at present; it has registered an increase of 25.59% as compared to 20.88 Million Hectare in 2009-10. However, with a production of about 319.57 Million Tonnes, horticulture production has witnessed an increase of about 43.25% during the period 2009-10 to 2019-20 (3rd Advance Estimates). The significant feature is that there has been improvement of productivity of horticulture crops which increased by about 14.06% during this period. ''')

spacy.displacy.render(doc, style="ent", jupyter=True) # display in Jupyter

nlp_ner

doc.ents